### ISSUE TITLE
Using ARIA tab roles without expected interaction behaviour

### ISSUE THREAD

**Issue by stevefaulkner** [vigetlabs/interactive-wcag#1]
ARIA tabs have associated keyboard interaction behaviours that need to be implemented. See design pattern details: http://www.w3.org/WAI/PF/aria-practices/#tabpanel

**Comment by stevefaulkner** [comment]
btw really like what you have done!

**Comment by ten1seven** [comment]
Thanks for the ticket, Steve!

Gosh, what kind of fool puts out an accessibility tool and forgets to test for accessibility? (I'm the fool)

I'll look at the live filters as well.

**Comment by ten1seven** [comment]
Added [bootstrap-accessibility-plugin](https://github.com/paypal/bootstrap-accessibility-plugin) to get the tabs working. Will create a new issue to make sure the form fields are more accessible.
