### ISSUE TITLE
Link checkpoints directly to WCAG 2.0 "Understanding" guidance and other resources

### ISSUE THREAD

**Issue by MarcusJT** [vigetlabs/interactive-wcag#4]
I think the tool shows great promise but as it stands it's simply too limited as it doesn't link out to any of the related content/guidance/code examples provided by W3C and others (apart from two generic links at the very bottom) which presents an obstacle to the reader (likely a developer) who wishes to learn more.

Instead, for guideline "1.1.1 - Non-text Content" I'd like to see that string hyperlinked to http://www.w3.org/TR/UNDERSTANDING-WCAG20/text-equiv-all.html and a link to http://squizlabs.github.io/HTML_CodeSniffer/Standards/WCAG2/1_1_1 included (see http://squizlabs.github.io/HTML_CodeSniffer/Standards/WCAG2/ if you're unfamiliar with that excellent resource) so that the reader can reach all of that information with a single click, making your tool infinitely more useful.

And of course that goes for all the guidelines, I'm simply using the first one as an example.

**Comment by ten1seven** [comment]
Thanks Marcus! Sorry I missed seeing this suggestion sooner!

**Comment by ten1seven** [comment]
Added main links to W3.org understanding docs. Will add additional links as time allows.
